### PR TITLE
Oredictionary unification

### PR DESCRIPTION
**Pull request by Sunconure11**
This should make the crops more compatible with harvestcraft and pretty
much any other agriculture mod.

### CODE REVIEW

**Comment by Wabbit0101** [comment]
Isn't this going to break all other mods that have already integrated with PMP? The code replaces the old ids with the new ones instead of adding to old ones. Will this be part of a major version update or will other mod recipes break with a minor update change?

**Comment by Sunconure11** [comment]
I am not aware of many mods with integration for PMP. This was done to integrate it better with pretty much everything else.

Also the codebase is weird so I cannot exactly add multiple definitions yet.

**Comment by larrythemodder** [comment]
@Sunconure11 I went ahead and updated the food classes (plantmegapack.object.PMPFood.java, plantmegapack.item.PMPItemFood.java) to support multiple OreDict names. The other classes can be changed similarly.

**Comment by Sunconure11** [comment]
Give me an example of using multiple oredictionaries on an item in this mod, this codebase is incredibly weird.

**Comment by larrythemodder** [comment]
@Sunconure11 I agree, PMP's code is quite unusual. Right now, multiple OreDictionary definitions would be added in plantmegapack.object.PMPFood.java.
```public enum PMPFood {
	foodAcaiberry(new String[]{"cropAcaiberry"}, PMPFoodType.berr, 1, 0.1F, -1, EnumSet.of(PMPFoodUse.frdr, PMPFoodUse.tead, PMPFoodUse.tree)),
	foodBeautyberry(new String[]{"cropBeautyberry"}, PMPFoodType.berr, 1, 0.1F, -1, EnumSet.of(PMPFoodUse.dess, PMPFoodUse.frdr)),```
The new String[]{} is where all OreDictionary definitions are currently registered. I'm thinking about replacing this with a more normal system.

**Comment by Sunconure11** [comment]
So which of these would be valid? Because I still don't get it.

`foodBeautyberry(new String[]{"cropBeautyberry"}, {"foodBeautyberry"}`

`foodBeautyberry(new String[foodBeautyberry]{"cropBeautyberry"}`

**Comment by larrythemodder** [comment]
@Sunconure11 It's a Java array, so what you would want to do is:
```
foodBeautyberry(new String[]{"cropBeautyberry", "foodBeautyberry"}, ...
```
However, I've been moving OreDictionary stuff over to a new file, so you won't need to use this method. I'll be pushing a commit later today that will make the changes for all foods. It will also make PMP work much better with NEI/JEI by reducing the recipe count from the 60k+ it's currently at.

**Comment by Sunconure11** [comment]
I forgot entirely about this, how are oredictionaries currently handled? Still this same method?

**Comment by larrythemodder** [comment]
I've moved all food items over to plantmegapack.core.PMPOreDictionary.java and plan to eventually move all items and blocks to that file. In that file, you just register them with OreDictionary.regsisterOre. The method detailed above is no longer used. For everything else, look in plantmegapack.object and plantmegapack.plant for OreDictionary.

**Comment by Sunconure11** [comment]
I see. I'll look into it when I can.

**Comment by Sunconure11** [comment]
Uh.

http://10paksmods.net/

Check 10pak's site.

**Comment by larrythemodder** [comment]
@Sunconure11 This is great news! I'll put a notice in this repo's description saying this project is halted.

**Pull request merged**
